### ISSUE TITLE
Chat Spam (Not a bug)

### ISSUE THREAD

**Issue by SkylineLights** [heatseeker0/Magitek-Beginnings#1]
Not really a bug, but the server tends to spam chat when it clears lag.
![2019-05-06_15 57 44](https://user-images.githubusercontent.com/50340652/57251641-4d4e1680-7018-11e9-9e37-67eb360009f1.png)

**Comment by drheat** [comment]
That spam is because you're OP. Normal users don't see this.

**Comment by drheat** [comment]
Fixed in https://github.com/heatseeker0/Magitek-Beginnings/commit/3ebc59d8abf7d0e90167db5bdb640a703473a483
