### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by Venom1987** [heatseeker0/Magitek-Beginnings#3]
Pack crashed while Starting. Here is the Crash Log. Appears to be a one time thing, but maybe this is interesting. 

https://pastebin.com/Bv5Jw8vv

**Comment by drheat** [comment]
Your Java version is very old and causes these type of issues. Upgrade Java on your computer, 1.8.0_200 is recommended or higher. Then tell Twitch client to use this version by passing the option `-version:1.8+`
in the additional arguments and it should use whichever is the latest you have on your PC.
